### ISSUE TITLE
Set up deployment of loklak_webclient on Heroku

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_webclient#620]
Currently the main loklak deployment on Heroku is broken. Please set up a deployment on your Heroku account and do the necessary. Once it is working we can do the same for the automatic deployment from the repo.

**Comment by palnabarun** [comment]
@mariobehling Can you please explain the issue? Is it regarding adding a script to automatically deploy the application on Heroku?

**Comment by abishekvashok** [comment]
@mariobehling, working on it I will send a link of the app once I deploy it to heroku. Then we can move on with automatic deployment.

**Comment by abishekvashok** [comment]
@mariobehling giving up, we can't deploy to heroku now, the web-client is not correctlyinstalled, ./install_heroku.sh return random errors after fixing one after other. Further the packages, dependencies used etc are really out of dat. We would nee a great amount of code refractor

**Comment by shikhar-scs** [comment]
Is this still up ? @mariobehling

**Comment by mariobehling** [comment]
Open for anyone who would like to try.

**Comment by shikhar-scs** [comment]
Ok I'm on it

**Comment by shikhar-scs** [comment]
I've followed all the procedures and steps for building the webclient. 
i.e setting up the api credentials, the apiURL, the loklak_server [here](https://github.com/loklak/loklak_server) which actually gets built and is working .
next running the node server at iframely, basically all of it.

However, whenever I run gulp dev as the final step I get this error 
```
gulp dev
/home/shikhar/Desktop/fossasiaLoklak/loklak_webclient/node_modules/karma/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/shikhar/Desktop/fossasiaLoklak/loklak_webclient/node_modules/karma/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/shikhar/Desktop/fossasiaLoklak/loklak_webclient/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:635:30)
```

Also the tests for youtube-scraper are failing everytime

**Comment by abishekvashok** [comment]
@shikhar-cs this is because of old node modules and a new node, updating will lead to other errors though.
